# MoPhones dbt project
# Supports: ongoing collections & credit analysis; consistent linkage between credit metrics and NPS.
name: mophones_data
version: "1.0.0"
config-version: 2
profile: mophones_data

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # Default reporting currency/units if needed
  days_past_due_buckets: ["Current", "1-30", "31-60", "61-90", "90+"]

models:
  mophones_data:
    staging:
      +schema: staging
      +materialized: view
      +tags:
        - staging
        - credit
        - nps
    intermediate:
      +schema: intermediate
      +materialized: view
      +tags:
        - intermediate
        - credit
        - collections
    marts:
      +schema: marts
      +materialized: view
      +tags:
        - marts
        - credit
        - nps
        - reporting

seeds:
  mophones_data:
    +schema: raw
