# dbt profile for MoPhones (BigQuery).
# Copy to ~/.dbt/profiles.yml or set DBT_PROFILES_DIR.
# Replace project/dataset with your BigQuery project and dataset.
mophones_data:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: your-gcp-project
      dataset: mophones
      threads: 4
    prod:
      type: bigquery
      method: oauth
      project: your-gcp-project
      dataset: mophones
      threads: 4
